### ISSUE TITLE
Bug report: window cycle list unexpected behaviour

### ISSUE THREAD

**Issue by kurokawachan** [mati75/openbox-debian#22]
## How to reproduce issue

- close all windows 
- create seven different folders on your desktop, namingly 1 2 3 4 5 6 7
- open the seven folders into seven different windows
- click on the seven folders in the order of 1 2 3 4 5 6 7 to make sure each window get focused once. 
- Now, if you press alt-tab without releasing. you would see inside the window cycle list, from top to bottom, the windows are 7 6 5 4 3 2 1
- Press esc to close the alt-tab window cycle list 
- Press win-d to show the desktop 
- Press alt-tab once and release, you would see window 7 is focused
- Press alt-tab once and release, you would see window 6 is focused
- Press alt-tab once and release, you would see window 7 is focused
- Press win-d to show the desktop
- Now, if you press alt-tab without releasing. you would see inside the window cycle list, from top to bottom, the windows are 7 6 5 4 3 2 1
- Attention, now is the issue, release the key, you would see window 7 is focused, and it is the only window on screen
- Now, if you press alt-tab without releasing. you would see inside the window cycle list, from top to bottom, the windows are 7 5 4 3 2 1 6
- why window 6 is not where it used to be?

**Comment by mati75** [comment]
This is not upstream repository, please report it here http://openbox.org/contribute#Bug_reports
